services:
  redis:
    image: redis:alpine
    container_name: redis-tabby
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes


  redisinsight:
    image: redis/redisinsight:latest
    container_name: redis-ui-tabby
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 5540:5540
    volumes:
      - redisinsight:/data
    depends_on:
      - redis

volumes:
  redis_data:
  redisinsight: